// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ZfggddKsnyfHXrGVgWa6D_m-rCzMEQc',
    appId: '1:99478645576:web:bbdb08c4a5700d1cc2617d',
    messagingSenderId: '99478645576',
    projectId: 'lab-automation-9c5d5',
    authDomain: 'lab-automation-9c5d5.firebaseapp.com',
    databaseURL: 'https://lab-automation-9c5d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab-automation-9c5d5.appspot.com',
    measurementId: 'G-F5GNP5BHBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgNfBqGekcu863QjzYLyi2mJ_6dzLLtE',
    appId: '1:99478645576:android:4b260794aed7fca8c2617d',
    messagingSenderId: '99478645576',
    projectId: 'lab-automation-9c5d5',
    databaseURL: 'https://lab-automation-9c5d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab-automation-9c5d5.appspot.com',
  );
}
